[AAP-3256] Added rst doc for multiple events
benthomasson/ansible-events pull request #114
Opened 2022-07-19 14:20 UTC by mkanoor

https://issues.redhat.com/browse/AAP-3256

Some of the caveats mentioned in the docs will be worked
on in subsequent sprints

2022-07-19 14:20 UTC, mkanoor commented
@benthomasson Please review

2022-07-21 14:01 UTC, benthomasson requested changes

2022-07-21 14:01 UTC, benthomasson commented on docs/multi_events.rst
> +4. Currently there is no time constraint when satisfying multiple event conditions. We are planning on implementing a **within** syntax which will be aking to all with the added time constraint::
Let's document the features that exist right now.

2022-07-21 17:51 UTC, mkanoor commented
@benthomasson Please review, I have removed the caveats

2022-07-26 19:59 UTC, benthomasson approved these changes

2022-07-26 20:03 UTC, merged