Support var_root in multi events
benthomasson/ansible-events pull request #119
Opened 2022-07-25 20:00 UTC by mkanoor

var_root is used to optionally lift up the keys in a nested events
dictionary.
The var_root has been modified to take in a sigle nested key in the form
of a.b.c or or a list of keys of the form
- a.b.c
- x.y.x

When we have matching on multiple events from different sources the
event payload could have different keys. The var_root can store the
nested keyname for different payloads and pick them from different
events.

If the var_root has the following keys
   ['webhook.payload', 'kafka.message']

it can modify the events from

{'events': {'webhook': {'webhook': {'payload': {'url': 'http://www.example.com', 'action': 'merge'}}},
            'kafka': {'kafka': {'message': {'topic': 'testing', 'channel': 'red'}}}}

to

{'events': {'webhook': {'url': 'http://www.example.com', 'action': 'merge'},
            'kafka': {'topic': 'testing', 'channel': 'red'}}

2022-07-25 20:00 UTC, mkanoor commented
@benthomasson Please review

2022-07-26 20:13 UTC, benthomasson requested changes

2022-07-26 20:13 UTC, benthomasson commented on tests/test_examples.py
> +async def test_23_multiple_events_var_root():
Please change the name to test_27_multiple_events_var_root

2022-07-28 15:15 UTC, cutwater commented on ansible_events/builtin.py
> +    var_root: Optional[Union[str, List[str]]] = None,
The type hint here can be slightly simplified as :

```Union[str, List[str], None]```

since `Optional[T]` is the same as `Union[T, None]`

2022-08-02 14:29 UTC, mkanoor commented
Closed in favor of https://github.com/benthomasson/ansible-events/pull/126

2022-08-02 14:29 UTC, closed without merging