Fixed a bug in non string type in facts
benthomasson/ansible-events pull request #121
Opened 2022-07-26 21:19 UTC by mkanoor

- Missing a return statement
- Modified print_event to send the variables and facts in the event log
  for comparison when runnin under pytest

2022-07-26 21:19 UTC, mkanoor commented
@benthomasson Please review

2022-07-27 11:51 UTC, benthomasson requested changes

2022-07-27 11:51 UTC, benthomasson commented on tests/examples/04_assert_fact.yml
> +            alpha: 1
Make a new test for this instead of changing one of the examples.  Add the test to test_engine instead of test_examples.

2022-07-28 14:18 UTC, benthomasson approved these changes

2022-07-28 14:18 UTC, merged