Added flake8 config setting
benthomasson/ansible-events pull request #129
Opened 2022-08-02 18:46 UTC by mkanoor

When we run flake8 locally we want to be able to skip
the venv and cache and other directories.

2022-08-02 18:46 UTC, mkanoor commented
@benthomasson Please review

2022-08-03 13:55 UTC, cutwater requested changes
1. Flake8 settings are stored in the `setup.cfg`. Please use this configuration file if further `flake8` customization is required.
2. Flake8 excludes `.git` and `__pycache__` directories by default. Setting `exclude` option overrides default exclude list. Please use `extend-exclude` to add excluded directories.

2022-08-03 15:01 UTC, cutwater requested changes

2022-08-03 15:01 UTC, cutwater commented on setup.cfg
> +extend-exclude = docs, venv
Should it include `.venv` as well?

2022-08-03 16:06 UTC, cutwater approved these changes
Please don't forget to squash your commits before merging.

2022-08-04 14:00 UTC, benthomasson approved these changes

2022-08-04 14:00 UTC, merged