Fixing error handling for the websocket connection
benthomasson/ansible-events pull request #141
Opened 2022-08-19 17:20 UTC by benthomasson

2022-08-22 14:55 UTC, benthomasson commented
@cutwater @mkanoor  please review

2022-08-22 15:00 UTC, cutwater requested changes

2022-08-22 15:00 UTC, cutwater commented on ansible_events/websocket.py
> +    logger = logging.getLogger("ansible_events.websocket")
Logger can be initialized globally. No need to perform a lookup at every function call.

2022-08-22 15:00 UTC, cutwater commented on ansible_events/websocket.py
> +    logger.info(f"websocket {websocket_address} connecting")
Better to pass log message parameters separately and allow logging to format message for you:

```suggestion
    logger.info(f"websocket %s connecting", websocket_address)
```

2022-08-23 11:34 UTC, cutwater requested changes

2022-08-23 11:34 UTC, cutwater commented on ansible_events/websocket.py
>              continue
Since there is no logic below the `try: ... except:` block, the `continue` statements are redundant here.

2022-08-23 18:27 UTC, cutwater requested changes

2022-08-23 18:27 UTC, cutwater commented on ansible_events/websocket.py
> +            pass
`pass` statement is not needed as well. The `pass` statement is only useful for empty blocks.

2022-08-23 18:28 UTC, cutwater approved these changes

2022-08-23 19:03 UTC, merged