[AAP-5126] Allow to rerun a playbook on failure
benthomasson/ansible-events pull request #147
Opened 2022-08-25 21:47 UTC by bzwei

Add option retry: True to rerun a playbook on failure,
or retries: <count> to retry multiple times until succeed.
Option retry_interval: <seconds> to pause a few seconds before rerun.

The same options can be applied to rerun a module.

See tests/examples/33_run_playbook_retry.yml or
tests/examples/34_run_playbook_retries.yml or
tests/examples/32_run_module_fail.yml for examples.

Resolves: AAP-5126

2022-08-26 08:36 UTC, Alex-Izquierdo reviewed
IMO the `retry` boolean option is redundant and is not needed. 
Following the ansible-playbook behavior, defining a number of retries enables retrying implicitly:
https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#retrying-a-task-until-a-condition-is-met

Also I would like to consider, @benthomasson @bzwei 
Is it necessary a retry option here when ansible-playbook provides that feature?

2022-08-26 13:37 UTC, bzwei commented
@Alex-Izquierdo Surely we can remove the boolean option, but I followed the requirement from AAP-5126. I think this feature is useful when we don't have the ability to edit the playbook.
I will change the option `retry_interval` to `delay`.

2022-08-30 11:57 UTC, benthomasson requested changes
Please update schema/ruleset_schema.json with the new options.  Run a schema validator on  your examples to check it.

2022-08-31 17:19 UTC, benthomasson approved these changes

2022-08-31 17:20 UTC, merged