Removed + syntax of is defined
benthomasson/ansible-events pull request #151
Opened 2022-09-02 12:33 UTC by mkanoor

To check if an object.attribute exists use is defined

e.g
event.j is defined

2022-09-02 12:33 UTC, mkanoor commented
@benthomasson Please review

2022-09-07 18:00 UTC, benthomasson requested changes

2022-09-07 18:00 UTC, benthomasson commented on ansible_events/rule_generator.py
> +            raise Exception("Please use is defined instead of +")
Add quotes around 'is defined'

2022-09-07 18:58 UTC, mkanoor commented
@benthomasson Please review I have added quotes around is defined

2022-09-07 19:03 UTC, benthomasson approved these changes

2022-09-07 19:03 UTC, merged